irods/irods_client_icommands

src/ichksum.cpp
ichksum can now be run with the '-M' option to run the command in admin mode. This allows admin users to ichksum files that they do not have permissions for.
(partial copy from 4-1-stable SHA: 3c8189a3214ad26c5110e5e21f934cb7ee55f178) (from https://github.com/irods/irods)
See accompanying change in [irods/irods#3809](https://github.com/irods/irods/pull/3809)
=> [irods/irods#3265] Add admin flag to ichksum

src/iinit.cpp
Without this, an execution of iinit will pick up the existing session from the user's system (if it exists from a prior iinit) and not perform a full re-authentication flow.  Specifying a context string to clientLoginOpenID overrides that behavior in the auth plugin.
=> [irods/irods#3945] add provider to iinit login

src/iadmin.cpp
obfEncodeByKeyV2 requires the challenge string from the server, which confounds decoding when not connected directly to a catalog provider. obfEncodeByKey works solely based on encoding the new password with another password (in all cases currently, specifically the password of the user calling it). This allows us to change the password even if we are not connected to a catalog provider server.
=> [#47] Change iadmin to use obfEncodeByKey

src/iapitest.cpp, src/iclienthints.cpp, src/izonereport.cpp
spOption is the environment variable that the server checks to identify a connected client. This variable should be set for all the icommands. izonereport, iapitest, and iclienthints do not set this environment
variable. In the case of izonereport and iclienthints, the -h flag was actually not supported at all, despite claiming to have support.
---
[Passed CI tests.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1081/)
=> [irods/irods#3991] Set spOption everywhere

src/iapitest.cpp, src/iclienthints.cpp, src/izonereport.cpp
spOption is the environment variable that the server checks to identify a connected client. This variable should be set for all the icommands. izonereport, iapitest, and iclienthints do not set this environment
variable. In the case of izonereport and iclienthints, the -h flag was actually not supported at all, despite claiming to have support.
(cherry-picked from SHA: 008b5343e086e452cbf62173d94fc4f8fbafd05a)
---
[Passed CI tests.](http://172.25.14.125:8080/job/irods-build-and-test-workflow/1097/)
=> [irods/irods#3991] Set spOption everywhere (4-2-stable)

src/irods-grid.cpp
Depends on:  [irods/externals#15]
std::auto_ptr was removed from the C++17 standard.
Passed CI.
=> [#64] Removed std::auto_ptr so that project builds using C++17.

src/iuserinfo.cpp
Refactor to use query iterator and recognize zone names. The client
has changed to follow these constraints:
1. The current user is implied when there is no input
2. The current zone is implied when no zone is supplied
In this way, each run of iuserinfo prints a unique user as users are
unique within zones.
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1752/)
Tests and query iterator changes in PR irods/irods#4242
=> [irods/irods#4194] Honor zone name in iuserinfo (master)

src/iuserinfo.cpp
Refactor to use query iterator and recognize zone names. The client
has changed to follow these constraints:
1. The current user is implied when there is no input
2. The current zone is implied when no zone is supplied
In this way, each run of iuserinfo prints a unique user as users are
unique within zones.
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1751/)
Tests in PR irods/irods#4243
=> [irods/irods#4194] Honor zone name in iuserinfo (4-2-stable)

src/ipwd.cpp
=> [irods/irods#4060] ipwd now escapes '\f' properly.

src/iuserinfo.cpp
The data backing the pointer returned by `std::string::c_str()` only sticks around as long as the `std::string` object. In this case, the `std::string` object is only around long enough to return the pointer.
This also fixes a warning from clang 10.
Addresses irods/irods#5214
=> [irods/irods#5214] iuserinfo: fix use after free in main (master)

src/iuserinfo.cpp
Cherry-pick of #165
The data backing the pointer returned by `std::string::c_str()` only sticks around as long as the `std::string` object. In this case, the `std::string` object is only around long enough to return the pointer.
This also fixes a warning from clang 10.
Addresses irods/irods#5214
=> [irods/irods#5214] iuserinfo: fix use after free in main (4-2-stable)

src/iphymv.cpp
This change introduces more exit codes to iphymv based on a family of
error codes returned from the server in rsDataObjPhymv. Doing so allows
system implementers to take action based on a number of common use cases
such as retrying in the face of connection/network errors versus the
target replica being written to a node with a full disk.
---
Also added some more help text.
Should I add tests to irods/irods for the new error codes? Not sure how to easily trigger some of these situations...
Error codes...
0. Testing success is pretty extensive already
1. Testing various invalid inputs to `iphymv`, checking for error code 1
2. Testing failure to connect to server could just stop the server and run `iphymv`
3. Testing failure to authenticate as current user or anything besides codes 0-2 and …
=> [irods/irods#5360] Return more detailed codes in iphymv (master)

.gitignore, CMakeLists.txt, README.md, packaging/userspace/build_and_package.example.sh, packaging/userspace/chrpath.cmake, packaging/userspace/compat_shims.py, packaging/userspace/context.py, packaging/userspace/elfinfo_util.py, packaging/userspace/externs_libs.common, packaging/userspace/known_libs.centos7, packaging/userspace/known_libs.common, packaging/userspace/known_libs.ubuntu16, packaging/userspace/known_libs.ubuntu18, packaging/userspace/libdirectives.py, packaging/userspace/lief_instrumentation.py, packaging/userspace/log_instrumentation.py, packaging/userspace/options.py, packaging/userspace/pyproject.toml, packaging/userspace/runpath_util.py, packaging/userspace/script_common.py, packaging/userspace/strip_util.py, packaging/userspace/tar_util.py, packaging/userspace/userspace-packager.py, packaging/userspace/utilbase.py, src/itouch.cpp
Introduce packaging functionality for a userspace tarball.
Addresses irods/irods#5082
The current implementation is separate from our CPack packaging.
Requires Python 3. I'm targeting 3.6/3.5 for master/4-2-stable, which should ensure compatibility with all distros we currently support.
Will use `lief` if it is available, and will scream if it's not.
Here's the current process:
1. CMake adds the `userspace-tarball` target to the makefile. This target invokes the `userspace-packager.py` script and passes in a ton of information.
2. The script invokes the installation makefile targets for the icommands, with the prefix set to a temporary workspace.
3. The icommands are stripped of unneeded symbols, and, if `lief` is available, any imported libraries that are no longer needed after stripping …
=> [irods/irods#5082] Introduce userspace tarball packaging functionality (master)

CMakeLists.txt, src/itree.cpp
The itree command can display an easy to digest visualization of a collection in irods.
It can print json with -J and display the total size of collections etc.
=> [irods/irods#5786] Implement itree command (4-2)

packaging/userspace/userspace-packager.py
Fixes irods/irods#5845 for master.
I haven't actually tested this against a running server yet.
My plan was to include GCC/libstdc++ compatibility changes in this PR (there might have to be special handling for libstdc++ like there is for libc++), but it turns out the problem with the GCC build that I was running into isn't actually related to packaging at all.
=> [irods/irods#5845] include api plugins in userspace tarball (master)

src/iadmin.cpp
Remove the zone option for iadmin moduser because changing a user's zone
is no longer allowed. Removed some of the username sanitizing which was
being performed by iadmin before calling the rcGeneralAdmin API. The
server should be responsible for checking these inputs.
Companion PR for irods/irods#5971
=> [irods/irods#4231] Remove options for iadmin (4-2-stable)

src/iadmin.cpp
Remove the zone option for iadmin moduser because changing a user's zone
is no longer allowed. Removed some of the username sanitizing which was
being performed by iadmin before calling the rcGeneralAdmin API. The
server should be responsible for checking these inputs.
=> [irods/irods#4231] Remove options for iadmin (master)

test/rules/rulemsiDataObjPhymv.r
corequisite with PR: https://github.com/irods/irods/pull/6206
(issue: https://github.com/irods/irods/issues/6169)
=> avoid USER_INCOMPATIBLE_PARAMS in Phymv rule file test (4-2-stable)

CMakeLists.txt
Addresses irods/irods#6261 for this repo for 4-2-stable
=> [irods/irods#6261] Declare that the icommands debian package provides itself (4-2-stable)

packaging/userspace/compat_shims.py, packaging/userspace/elfinfo_util.py, packaging/userspace/externs_libs.common, packaging/userspace/known_libs.centos7, packaging/userspace/known_libs.common, packaging/userspace/known_libs.debian11, packaging/userspace/known_libs.el8, packaging/userspace/known_libs.ubuntu18, packaging/userspace/known_libs.ubuntu20, packaging/userspace/libdirectives.py, packaging/userspace/lief_instrumentation.py, packaging/userspace/pyproject.toml, packaging/userspace/runpath_util.py, packaging/userspace/strip_util.py, packaging/userspace/userspace-packager.py, packaging/userspace/utilbase.py
This PR does the following:
- Updates directive files for supported distros
- Adds directive files for newly supported distros
- ~~Conditionally cleans out unneeded library imports with dangling symbol versions (lief-project/LIEF#670)~~ - later
Tested in containers:
Closes irods/irods#6276
=> [irods/irods_6276] Update userspace tarball packager

README.md
Useful for users who do not wish to build their own iCommands package
but just want to install the released packages.
=> [irods/irods#6559] Add instructions for installing irods-icommands (main)

src/ifsck.cpp
Addresses irods/irods#6626 / irods/irods#6051
Its presence suggests that ifsck takes multiple paths per invocation when in fact it does not.
=> [irods/irods#6626] Remove ellipsis from ifsck help text (main)

CMakeLists.txt, src/iadmin.cpp
Required to compile icommands and irods/irods#6718 with C++20 std.
=> [irods/irods#6725] icommands now compile using the same C++ standard as the server (main)

src/itouch.cpp
Ensures itouch returns a non-zero code when an error is ecountered.
=> [irods/irods#6434] Ensure itouch properly returns error code (4-2-stable)

src/itouch.cpp
=> [irods/irods_6434] Ensure itouch properly returns error code (4-3-stable)

src/iinit.cpp
Enable `iinit` to handle longer `$HOME` directory.
Cherry-pick of #336 or #352.
This did change a bit, since the filesystem library is not available for 4-2-stable.
=> [irods/irods_5411] Allow longer `HOME` directory in iinit (4-2-stable)

src/igroupadmin.cpp
Corresponds to changes in https://github.com/irods/irods/pull/6889 . `igroupadmin` was scrambling an empty password string when the  password parameter was not provided; this fixes that oversight.
=> [irods/irods#6887] send scrambled password only if param not empty (4-2-stable)

src/iqstat.cpp
Fix the things that are broken about `iqstat` options, and maybe even  a little more generally.  "Touch, improve."
- `iqstat -a <anything>` - caused agent crash which made the client report SYS_INTERNAL_ERR
* now, `<anything>` is scanned and rejected if not formatted as unsigned int.
* plus, `iqstat -a <unsigned_int_rule_id>` works now.  it reports all rule in the system regardless of the owning user
- where there were two routines, the brief and long version, they are now integrated into one.
- there may be more, i just can't remember right now. more later
- if any of these things expose security problems, let's discuss.
=> [irods#6740] shaping up iqstat (4-2-stable)

src/igroupadmin.cpp
These were mainly explanations detailing how a groupadmin must proceed to be able to add and remove users from a group they create.
Also changed some occurrences of "" to " " in the help text arrays, allowing the complete text to be printed in those cases.
=> [irods/irods#6888] extra help text documentation for igroupadmin (main)

src/igroupadmin.cpp
These were mainly explanations detailing how a groupadmin must proceed to be able to add and remove users from a group they create.
Also changed some occurrences of "" to " " in the help text arrays, allowing the complete text to be printed in those cases.
=> [irods/irods#6888] extra help text documentation for igroupadmin (4-3-stable)

src/itree.cpp
itree will now act more like `tree` (the Linux command) in that `--pattern` and `--ignore` use file globs.  The old sense of these options has been replaced by `--pattern-regex` and `--ignore-regex`.
=> [_6791] allow both regex- and glob-style matching (4-2-stable)

src/itree.cpp
A correction for `4-2-stable` only, as #340 is already merged with  an unnecessary `#include <cassert>`  [that sneaked in](https://github.com/irods/irods_client_icommands/pull/340/files#diff-2e6ca6ed53b52ed21049080a7ba80fb31aa8749940e967e466ec26a31bed972aR16) to the merged code.  Within the corresponding pulls (#369 and #370) to other branches, not yet merged, this change need not result in an additional pull request and may even be integrated into the main commit.
=> [_371] remove <cassert> include

src/itree.cpp
cherry-picked from https://github.com/irods/irods_client_icommands/pull/385
If the logical path argument given to itree is not an existing collection, we call this an error and return prematurely.
=> [irods/irods_6627] Output better error messages for invalid path arguments. (main)

src/itree.cpp
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/389
If the logical path argument given to itree is not an existing collection, we call this an error and return prematurely.
=> [irods/irods_6627] Output better error messages for invalid path arguments (4-3-stable)

src/itree.cpp
Rewrote help text to match look of `itouch` as well.
=> Updated itree help text to include warning about large collections (main)

CMakeLists.txt
In service of irods/irods#6412
Cherry-picked from #417 
Companion PR: https://github.com/irods/irods/pull/7394
I imagine this will be changed very soon due to irods/irods#7361?
=> [irods/irods#6412] Bump version number to 4.3.1. (main)

src/irm.cpp
Note that this option makes irm ignore non-existent data objects.
=> [irods/irods#7421] irm: expand docs force option (main)

src/irm.cpp
Note that this option makes irm ignore non-existent data objects.
=> [irods/irods#7421] irm: expand docs force option (4-3-stable)

CMakeLists.txt
In service of irods/irods#7531
Not removing `EXACT` from the `find_package(IRODS` call since the icommands are currently pretty tightly coupled to the irods version they target.
Merge irods/irods#7536 before merging this.
=> [irods/irods#7531] bump irods version requirement and allow usage of find modules (4-3-stable)

CMakeLists.txt
In service of irods/irods#7220
Merge irods/irods#7526 before merging this.
=> [irods/irods#7220] Do not explicitly build against libc++ (main)

src/ierror.cpp, src/iget.cpp, src/iput.cpp, src/irmdir.cpp, src/irule.cpp, src/itree.cpp
Ensure that all icommands set `SP_OPTION`. Used `set_ips_display_name(...)` for additional warning log if an error occurs.
=> [irods/irods#7470] Ensure icommands set SP_OPTION (main)

CMakeLists.txt
In service of irods/irods#7592
With the updated externals from irods/externals#246, building `ierror`, `ienv`, and `ipwd` fails on Centos 7 with the following error:
```
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/libstdc++_nonshared.a(system_error48.o): undefined reference to symbol '__cxa_free_exception@@CXXABI_1.3'
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: /usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm not sure what changed to cause this to happen, but passing `--no-as-needed` to the linker fixes it.
This PR does not need to …
=> [irods/irods#7592] Fix centos 7 build with new externals (main)

CMakeLists.txt
4-3-stable version of #477
In service of irods/irods#7592
With the updated externals from irods/externals#246, building `ierror`, `ienv`, and `ipwd` against libstdc++ fails on Centos 7 with the following error:
```
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/libstdc++_nonshared.a(system_error48.o): undefined reference to symbol '__cxa_free_exception@@CXXABI_1.3'
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: /usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm not sure what changed to cause this to happen, but passing `--no-as-needed` to the …
=> [irods/irods#7592] Fix centos 7 build against libstdc++ with new externals (4-3-stable)

src/itree.cpp
This doesn't require testing. It's just help text.
I opened an issue for test coverage. See irods/irods#7825. We'll handle that post 4.3.3.
=> [#7761] Fix help text for itree JSON option (4-3-stable)

CMakeLists.txt
Companion to irods/irods#7895
In service of irods/irods#7759
=> [irods/irods#7759] Do not stamp iRODS version number on icommands package (4-3-stable)

CMakeLists.txt
Companion to irods/irods#7884
In service of irods/irods#7759
=> [irods/irods#7759] Do not stamp iRODS version number on icommands package (main)

src/imeta.cpp
Modeled this off of the other deprecations in `imeta`.
Question: should any of these messages explicitly mention the use of GenQuery (via `iquest` or otherwise) as a replacement?
=> [irods/irods7959] Deprecate imeta qu (4-3-stable)

src/iquest.cpp
=> [irods/irods#8088] Ignore deprecation of `fillGenQueryInpFromStrCond()` (4-3-stable)

CMakeLists.txt, src/ienv.cpp, src/ierror.cpp, src/ipwd.cpp
In service of #433
In service of irods/irods#7838
Addresses irods/irods#8122 for main
=> [#433,irods/irods#7838,irods/irods#8122] Fix EL8 build, remove old centos support code (main)

src/itree.cpp
Cherry-pick of https://github.com/irods/irods_client_icommands/pull/524
=> [irods/irods8082] Do not display stacktrace on exception (4-3-stable)

CMakeLists.txt, ub-sanitizer-ignorelist.txt
Cherry-pick of #518, compainion to irods/irods#8168.
No changes needed to cherry-pick.
---
This commit allows for the enabling of the Undefined Behavior Sanitizer (UBSAN). Nearly all of the options provided by UBSAN are enabled by default, with the exception of implicit conversions. A separate option exists to optionally enable implicit conversion checks.
=> [irods/irods#8090] Cherry-pick: Add Undefined Behavior Sanitizer Option to CMake (main)

src/imeta.cpp
In service of irods/irods#6766
Companion PR: https://github.com/irods/irods/pull/8263
Companion PR needs to go in first - it updates the tests to not use these subcommands.
=> imeta: Remove adda, lsw, addw, and rmw (main)

src/iput.cpp, src/irsync.cpp
Issue Quick Link: irods/irods#7578
Companion PR: irods/irods#8323
This PR removes the help text for `--link`, which is removed in the companion PR.
=> [irods/irods#7578] Remove `--link` from help text (main)

src/iinit.cpp
In service of irods/irods#2626
Companion PR: https://github.com/irods/irods/pull/8342
This needs to be merged at around the same time as the companion PR to prevent disruptions.
We might be able to get away with removing more of these prompts, but I would consider that a separate effort from this PR.
=> [irods/irods#2626] iinit: Remove key, chain, and dhparams prompts (main)

src/irepl.cpp, test/rules/rulemsiDataObjRepl.r
Issue quick link: irods/irods#7594
Companion PR: irods/irods#8340
This PR removes help text on backup mode, as well as removes `B` from the optStr.
=> [irods/irods#7594] Remove mentions of backup mode in icommands (main)

src/iinit.cpp
Cherry-picked from #557.
Had to handle one difference between branches, but otherwise, I think this is ready for squashing. Updated all calls involving `strncpy`.
I think the changes are obvious and do not require additional testing.
=> [irods/irods#8379] Guarantee rodsEnv strings are null-terminated (4-3-stable)

test/rules/rulemsiAclPolicy.r
Issue quick link: irods/irods#7985.
Companion to PR: irods/irods#8264.
This PR just removes a test containing `msiAclPolicy`.
=> [irods/irods#7985] Remove test containing `msiAclPolicy` (main)
