irods/irods_client_icommands

src/ireg.cpp
Passed Jenkins.  Required for pull request that references issue 3828.
=> Half of the solution for issue 3828

src/ipasswd.cpp
#3580 ipasswd issues (was: stty path hard-coded in clientLogin.cpp)
=> 42stable hardcoded path 3580

src/iinit.cpp
=> [#49] Updated iinit's help text relating to passwords.

src/irule.cpp
Corresponds to PR for  [addition of test_irule in irods/irods](https://github.com/irods/irods/pull/4208)
This fix addresses an [irule issue](https://github.com/irods/irods/issues/4189)
=> Irule inpparam fix

src/iinit.cpp
Tied to changes to irods here:
https://github.com/irods/irods/pull/4154
The function clientLoginOpenID no longer exists after PR irods/irods#4154
The ctx key 'iinit_arg' is used by the openid auth plugin to perform non-interactive login flows.  An api key or token can be passed as the 1st command argument (referred to as `password`).  The openid plugin handles this value according to:
https://github.com/irods-contrib/irods_auth_plugin_openid/blob/7c97782735ca328ad541d69bcdd1d1da1bd9c724/src/libopenid.cpp#L644-L657
=> Changes for openid in iinit (master)

src/ipasswd.cpp
cherry-pick of 91ca6ed2071bf7a763bcf8fb127b25091aaad122
=> [irods/irods#3972] enforce password size limit (master)

src/irmdir.cpp
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1766/)
=> [irods/irods#4000] Fix no args core dump for irmdir (4-2-stable)

src/irmdir.cpp
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1765/)
=> [irods/irods#4000] Fix no args core dump for irmdir (master)

src/iexit.cpp
tests included in https://github.com/irods/irods/pull/4263
=> [irods/irods2082] update iexit to always remove saved credential file

src/iuserinfo.cpp
=> [irods/irods#4296] Use template params in qobjs (4-2-stable)

src/iuserinfo.cpp
(cherry-picked from e4932b31c288b3ed4dda272e3e6a122225d7abaf)
=> [irods/irods#4296] Use template params in qobjs (master)

CMakeLists.txt, src/iinit.cpp, src/irods-grid.cpp
CI tests passed. Needed for irods/irods#4630
=> [irods/irods#4627] Enable C++17 support

CMakeLists.txt, src/istream.cpp
Requires upgraded build tools (e.g. Clang, C++17, etc.)
=> [irods#4626] Added new icommand: istream (4-2-stable)

CMakeLists.txt, src/irm.cpp, src/iunreg.cpp
All tests pass in CI except where noted in linked irods/irods issue. Requires irods/irods#4729 to be merged.
=> [irods/irods#4506] Add iunreg, deprecate irm -U (master)

CMakeLists.txt, src/irm.cpp, src/iunreg.cpp
CI tests are running.
Requires irods/irods#4730
=> [irods/irods#4506] Add iunreg, deprecate irm -U (4-2-stable)

src/iadmin.cpp
iadmin modrepl can be used to modify a number of different columns in
R_DATA_MAIN. Some have been restricted until such a time as a valid use
case justifies its exposure in the client. Until then, only a subset of
the columns are modifiable via iadmin modrepl.
iadmin ls now lists the GenQuery attributes and their values which map to
the columns of R_DATA_MAIN. This is mainly for convenience.
---
CI tests running
=> [irods/irods#4740] Add iadmin modrepl and ls (master)

src/iadmin.cpp
iadmin modrepl can be used to modify a number of different columns in
R_DATA_MAIN. Some have been restricted until such a time as a valid use
case justifies its exposure in the client. Until then, only a subset of
the columns are modifiable via iadmin modrepl.
iadmin ls now lists the GenQuery attributes and their values which map to
the columns of R_DATA_MAIN. This is mainly for convenience.
---
CI tests running
=> [irods/irods#4740] Add iadmin modrepl and ls (4-2-stable)

src/isysmeta.cpp
=> [irods/irods#4768] Replaced rcModDataObjMeta in isysmeta (master)

src/isysmeta.cpp
=> [irods/irods#4768] Replaced rcModDataObjMeta in isysmeta (4-2-stable)

test/rules/rulemsiSetMultiReplPerResc.r
=> [irods/irods#4408] Remove rulemsiSetMultiReplPerResc (master)

src/istream.cpp
This depends on irods/irods#5038
=> [irods/irods#5000] istream supports resource names, replica numbers, and computing checksums (master)

src/istream.cpp
=> [irods/irods#5000] istream supports resource names, replica numbers, and computing checksums (4-2-stable)

src/istream.cpp
Bundled with irods/irods#5113.
=> [irods/irods#5112] istream handles invalid integer values for -o and -c appropriately (master)

src/istream.cpp
Bundled with irods/irods#5114.
=> [irods/irods#5112] istream handles invalid integer values for -o and -c appropriately (4-2-stable)

CMakeLists.txt, src/itouch.cpp
Depends on the **touch** API plugin defined in this [PR](https://github.com/irods/irods/pull/5147).
Passes itouch tests.
=> itouch v2 (master)

src/imeta.cpp
This is meant to address irods/irods#5111.
Test will be in a separate pull request in the irods repository.
=> [irods/irods#5111] Implement long output for non-data objects in imeta ls (master)

src/imeta.cpp
The following issues are addressed by this PR:
- irods/irods#5021
- irods/irods#5101
- irods/irods#5102
- irods/irods#5184
- irods/irods#5185
=> [multiple] imeta error handling fixes (master)

src/imeta.cpp
#161 cherry-picked into stable
The following issues are addressed by this PR:
- irods/irods#5021
- irods/irods#5101
- irods/irods#5102
- irods/irods#5184
- irods/irods#5185
=> [multiple] imeta error handling fixes (4-2-stable) 

src/imeta.cpp
=> [irods/irods#5081] imeta interactive: do not exit on error status from do_command (master)

src/imeta.cpp
#163 cherry-picked into stable.
Addresses irods/irods#5081
Currently being pushed through jenkins, will update when done
=> [irods/irods#5081] imeta interactive: do not exit on error status from do_command (4-2-stable)

CMakeLists.txt
in service of irods/irods#5250
=> [irods/irods#5250] cmake: set version number in project call (master)

CMakeLists.txt
For more info, see https://github.com/irods/irods_testing_jenkins/issues/116
=> [irods/irods_testing_jenkins#116] "gzip -k" alternative for CentOS 7 (master)

CMakeLists.txt
For more info, see https://github.com/irods/irods_testing_jenkins/issues/116
=> [irods/irods_testing_jenkins#116] "gzip -k" alternative for CentOS 7 (4-2-stable)

src/ils.cpp
Depends on https://github.com/irods/irods/pull/5510
=> [irods/irods#5506] Added option to ils that skips printing collection's contents (4-2-stable)

src/ils.cpp
Depends on https://github.com/irods/irods/pull/5509
=> [irods/irods#5506] Added option to ils that skips printing collection's contents (master)

src/imeta.cpp
Fixes [irods #5518](http://github.com/irods/irods/issues/5518)
=> Allow quoted arguments in imeta interactive mode (4-2-stable)

src/iphymv.cpp
Cherry-picked from changes made for #201 
Companion PR: irods/irods#5574
CI tests running
=> [irods/irods#5360] Return more detailed codes in iphymv (4-2-stable)

.gitignore, CMakeLists.txt, README.md, packaging/userspace/build_and_package.example.sh, packaging/userspace/chrpath.cmake, packaging/userspace/compat_shims.py, packaging/userspace/context.py, packaging/userspace/elfinfo_util.py, packaging/userspace/externs_libs.common, packaging/userspace/known_libs.centos7, packaging/userspace/known_libs.common, packaging/userspace/known_libs.ubuntu16, packaging/userspace/known_libs.ubuntu18, packaging/userspace/libdirectives.py, packaging/userspace/lief_instrumentation.py, packaging/userspace/log_instrumentation.py, packaging/userspace/options.py, packaging/userspace/pyproject.toml, packaging/userspace/runpath_util.py, packaging/userspace/script_common.py, packaging/userspace/strip_util.py, packaging/userspace/tar_util.py, packaging/userspace/userspace-packager.py, packaging/userspace/utilbase.py, src/itouch.cpp
#196 backported to stable
Addresses irods/irods#5082
Here's what's left to be done:
=> [irods/irods#5082] Introduce userspace tarball packaging functionality (4-2-stable)

src/ils.cpp, src/imcoll.cpp
Fixes irods/irods#5721 for master
=> [irods/irods#5721] fix accidental string concat

CMakeLists.txt
In service of irods/irods#4083
=> [irods/irods#4083] buildsystem support for building with GCC

CMakeLists.txt, src/itree.cpp
=> [5786] itree command

packaging/userspace/userspace-packager.py
Cherry-pick of #228 into stable.
Fixes irods/irods#5845 for stable.
=> [irods/irods#5845] include api plugins in userspace tarball (4-2-stable)

src/ilsresc.cpp, src/iticket.cpp
This commit also fixes UTC display issues with the expiration timestamp for tickets. I need to investigate the UTC timestamps a little more.
Depends on irods/irods#5945
=> [#5933] Added admin option (-M) to iticket (master)

src/ilsresc.cpp, src/iticket.cpp
Cherry-picked from main/4.3 branch.
Needs review.
=> [#5933] Added admin option (-M) to iticket (4-2-stable)

src/iadmin.cpp, src/igroupadmin.cpp
Companion PR: irods/irods#6015
=> [#4231] Stop passing zone parameter to admin API (4-2-stable)

src/iadmin.cpp, src/igroupadmin.cpp
Companion PR: irods/irods#6016
=> [#4231] Stop passing zone parameter to admin API (master)

src/ilsresc.cpp
Depends on https://github.com/irods/irods/pull/6027
=> [#6022] ilsresc reports error on unknown zone name (4-2-stable)

src/ilsresc.cpp
Depends on https://github.com/irods/irods/pull/6033
=> [#6022] ilsresc reports an error on an unknown zone name (main)

CMakeLists.txt
=> [irods/irods_5669, irods/irods_5713] Update for new nlohmann-json

CMakeLists.txt
=> [irods/irods#6120] Add find_package() call for Threads (main)

CMakeLists.txt
=> [irods/irods#5479] Add -ldl CMake option for iCommands (main)

src/imeta.cpp, src/irods-grid.cpp, src/itree.cpp
TODO: Add test to irods/irods test suite.
=> itree relative paths fix, imeta updates, and cppzmq deprecation fix (main)

src/imeta.cpp, src/itree.cpp
TODO: Add test to irods/irods test suite.
=> itree correctly handles relative paths and imeta cp / admin mode (4-2-stable)

src/iquest.cpp
need to run through existing tests
=> [irods/irods4745] update iquest to return non-zero when CAT_NO_ROWS_FOUND

src/ireg.cpp
CI tests are running
Companion to https://github.com/irods/irods/pull/6203
=> [irods/irods#2919] Replace ireg -C with -r (main)

test/rules/rulemsiDataObjPhymv.r, test/rules/rulemsiSetRescSortScheme.r
corequisite with PR: https://github.com/irods/irods/pull/6170
(issue: https://github.com/irods/irods/issues/6169)
=> avoid USER_INCOMPATIBLE_PARAMS in Phymv rule file test

CMakeLists.txt
Addresses irods/irods#6261 for this repo for main
=> [irods/irods#6261] Declare that the icommands debian package provides itself (main)

src/iadmin.cpp
This PR builds upon the work of #262
=> [irods/irods#5249] add iadmin get_delay_server_info subcommand (main)

src/iinit.cpp, src/irule.cpp
Depends on https://github.com/irods/irods/pull/6332
=> Updated for variable renaming (main)

src/irm.cpp, test/rules/rulemsiDataObjUnlink.r
companion PR to irods/irods#6343
Tests running
=> Remove irm -U and -n (main)

src/imeta.cpp
cherry-picked from https://github.com/irods/irods_client_icommands/pull/297
=> [irods/irods_3062] better enumerate the operators for imeta qu (4-2-stable)

src/iinit.cpp, test/rules/rulemsiDataObjUnlink.r
companion PR for irods/irods#6358
Keeping as draft until proper testing is completed
=> [irods/irods#5479] Add new PAM iinit flow (main)

src/iinit.cpp
Companion PR: https://github.com/irods/irods/pull/6391
Still need to run through full test suite, but things were working when tested by hand
=> Fix native auth TTL and PAM prompt, remove options to show password in iinit (main)

src/iinit.cpp
companion PR: https://github.com/irods/irods/pull/6405
Due to the nature of iinit, certain code paths are taken for certain
auth plugins and not others. These are referenced directly by name in
the client application and not done in any sort of generic fashion. We
plan to implement a new iinit in the future with the iRODS client CLI,
so for now we will go along with the current implementation and directly
reference the pam_password plugin as one which should not display a
password prompt.
---
Confirmed that tests pass in testing environment.
=> [#5479] Use pam_password scheme name in iinit (main)

README.md
cherry-picked from #317 
(branch name was accident, sorry)
=> [irods/irods#6559] Add instructions for installing irods-icommands (4-3-stable)

README.md
=> [irods/irods#6559] Add instructions for installing irods-icommands (4-2-stable)

src/ifsck.cpp
Addresses irods/irods#6051
cherry-picked from #328
=> [irods/irods#6051] Remove ellipsis from ifsck help text (4-3-stable)

src/ifsck.cpp
Addresses irods/irods#6051
cherry-picked from #328
=> [irods/irods#6051] Remove ellipsis from ifsck help text (4-2-stable)

src/iadmin.cpp, src/icd.cpp
Addresses irods/irods#6624
All core tests passed. I applied clang-format to my changes using the file in irods/irods
=> [irods/irods#6624] iadmin: Replace SimpleQuery (main)

src/iadmin.cpp, src/icd.cpp
Addresses https://github.com/irods/irods/issues/6624
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/331
Requires https://github.com/irods/irods/pull/6655
=> [irods/irods#6624] iadmin: Replace SimpleQuery (4-2-stable)

CMakeLists.txt, src/iadmin.cpp
=> [irods/irods#6725] icommands now compile using the same C++ standard as the server (4-3-stable)

CMakeLists.txt, src/itree.cpp
Cherry-picked from #337.
Will add pounds once approved.
=> Added option to enable Address Sanitizer (4-3-stable)

src/iadmin.cpp, src/ils.cpp, src/ilsresc.cpp, src/imeta.cpp, src/iqdel.cpp, src/iqmod.cpp, src/iqstat.cpp, src/iquest.cpp, src/iquota.cpp, src/iticket.cpp, src/iuserinfo.cpp
Addresses irods/irods#6068
Addresses irods/irods#6365
Addresses irods/irods#6390
Companion PR: https://github.com/irods/irods/pull/6799
=> Catching exceptions and ensuring clients disconnect (main)

src/itree.cpp
=> Updated to match Filesystem library changes (main)

src/iadmin.cpp, src/ils.cpp, src/ilsresc.cpp, src/imeta.cpp, src/iqdel.cpp, src/iqmod.cpp, src/iqstat.cpp, src/iquest.cpp, src/iquota.cpp, src/iticket.cpp, src/iuserinfo.cpp
Addresses https://github.com/irods/irods/issues/6068
Addresses https://github.com/irods/irods/issues/6365
Addresses https://github.com/irods/irods/issues/6390
Companion PR: https://github.com/irods/irods/pull/6836
Cherry-picked from #342
=> Catching exceptions and ensuring clients disconnect (4-3-stable)

src/itree.cpp
Cherry-picked from #339
Depends on irods/irods#6845
=> Updated to match Filesystem library changes (4-3-stable)

src/itree.cpp
Cherry-picked from #346
Depends on irods/irods#6847
=> Updated to match Filesystem library changes (4-2-stable)

src/iadmin.cpp, src/ils.cpp, src/ilsresc.cpp, src/imeta.cpp, src/iqdel.cpp, src/iqmod.cpp, src/iqstat.cpp, src/iquest.cpp, src/iquota.cpp, src/iticket.cpp, src/iuserinfo.cpp
Addresses https://github.com/irods/irods/issues/6068
Addresses https://github.com/irods/irods/issues/6365
Addresses https://github.com/irods/irods/issues/6390
Companion PR: https://github.com/irods/irods/pull/6840
Cherry-picked and adapted from #342
=>  Catching exceptions and ensuring clients disconnect (4-2-stable)

src/iinit.cpp
Enable `iinit` to handle longer `$HOME` directory.
=> [irods/irods_5411] Allow longer `HOME` directory

src/iinit.cpp
=> [irods/irods_5411] Allow longer `HOME` directory in iinit

src/itouch.cpp
=> [irods/irods#6434] Ensure itouch properly returns error code (main)

src/irm.cpp
I've lumped this into the effort to address irods/irods#6896, but I'm open to making a dedicated issue for it.
=> [irods/irods#6896] irm: -n option should not be listed (main)

src/irm.cpp
In service of irods/irods#6896
Cherry-picked from #360
=> [irods/irods#6896] irm: -n option should not be listed (4-3-stable)

src/iinit.cpp
This change adds pam_interactive for consideration in the various twists and turns of logic in iinit. The changes mainly have to do with refactoring how iinit determines whether or not to show the password prompt.
---
Servicing irods/irods#6576
Based on work done by @stefan-wolfsheimer:
https://github.com/stefan-wolfsheimer/irods_client_icommands/commit/2c188dec8c7d0d40dad60bd5785fb30dcf7ae89c
Some other notes...
- I have only confirmed so far that this builds. Still needs to be tested
- `PAM_INTERACTIVE_SCHEME` would ideally be found as a string defined by a header in the `pam_interactive` auth plugin (like `native` and `pam_password` do)
- I am assuming that `pam_interactive` will not be available in the 4.2.x series
=> [irods/irods#6576] Add pam_interactive to iinit (main)

src/iinit.cpp
Addresses irods/irods#6576
Cherry-picked from #324
=> [irods/irods#6576] Add pam_interactive to iinit (4-3-stable)

src/itree.cpp
=> [#6791] allow both regex- and glob-style matching (main)

src/itree.cpp
Corresponding to https://github.com/irods/irods/pull/6946
=> [#6791] allow both regex- and glob-style matching (4-3-stable)

src/iexit.cpp
Prerequisite: irods/irods#6969
Addresses irods/irods#6136 for main
Will backport to stable branches after reviews done.
=> [#6136] iexit: avoid removing auth file for service account (unless forced) (main)

src/iexit.cpp
Backport of #379 to 4-3-stable.
Prerequisite: irods/irods#6990
=> [#6136] iexit: avoid removing auth file for service account (unless forced) (4-3-stable)

src/iexit.cpp
Backport of #379 and #382 to 4-2-stable.
Prerequisite: irods/irods#6996
=> [#6136] iexit: avoid removing auth file for service account (unless forced) (4-2-stable)

src/itree.cpp
=> Updated itree help text to include warning about large collections (4-3-stable)

src/itree.cpp
=> Updated itree help text to include warning about large collections (4-2-stable)

src/iticket.cpp
Update makeFullPath to actually return full path of object or collection
=> [irods 7103] Add relative path support to iticket (main)

src/iticket.cpp
Update makeFullPath to actually return full path of object or collection
=> [irods/irods 7103] Add relative path support to iticket (4-3-stable)

src/iinit.cpp
Addresses irods/irods#6398
Yielding to #336 due to inevitable merge conflicts
Still need to run tests. Still a ways to go here, but putting this up here so we can have something to point at.
Some issues/discussion points:
- Option names
- Lots of repeated code when dealing with the integer-based settings (encryption)
- Some workarounds/shims I'm not happy with (e.g. `_reloadRodsEnv`, forced `--always-save-environment` with `--with-ssl`)
- Should we add other options? `--disable-ssl`?
- Should we provide default values for the existing prompts?
=> [irods/irods#6398] iinit: Add options for auth scheme and SSL (main)

src/iinit.cpp
Addresses irods/irods#3164
Addresses irods/irods#6398
Cherry-picked from #338 
Companion PR: https://github.com/irods/irods/pull/7204
=> [irods/irods#3164][irods/irods#6398] iinit: Scheme and SSL prompts (4-3-stable)

src/ichmod.cpp
=> [irods/irods#6809] Updated ichmod help text (4-3-stable)

src/ilsresc.cpp, src/imeta.cpp, src/iquest.cpp, src/iticket.cpp
Companion PR to irods/irods#7269.
=> Address Sanitizer fixes (main)

CMakeLists.txt
=> [irods/irods#7263] CMake consistency sweep (4-3-stable)

src/iadmin.cpp
In service of irods/irods#7098
Companion PR: https://github.com/irods/irods/pull/7245
Will take out of draft when https://github.com/irods/irods/pull/7245 is out of draft.
=> [irods/irods#7098] iadmin: Add pam_password config subcommands (main)

src/iadmin.cpp
Addresses irods/irods#7283
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/407
=> [irods/irods#7283] iadmin: Add set_grid_configuration (4-3-stable)

src/irule.cpp
=> [irods/irods_6224] remove unused test mode from irule (main)

src/imeta.cpp
This will display the command name alongside the connection information (spOption).
=> [irods/irods#7376] imeta: add set_ips_display_name call (main)

src/imeta.cpp
Addresses irods/irods#7376
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/426
=> [irods/irods#7376] imeta: add set_ips_display_name call (4-3-stable)

src/itrim.cpp
In service of irods/irods#7502
In service of irods/irods#7498
Companion PR: irods/irods#7500
=> itrim: Note deprecated options (main)

src/itrim.cpp
=> itrim: Note deprecated options (4-3-stable)

src/iadmin.cpp
Addresses irods/irods#7503
Also added the available namespaces/options for each command so you don't have to go look it up in the catalog.
=> [irods/irods#7503] iadmin: Enhance get/set_grid_configuration help text (main)

src/iadmin.cpp
=> [irods/irods#7503] iadmin: Enhance get/set_grid_configuration help text (4-3-stable)

CMakeLists.txt
In service of irods/irods#6251
=> [irods/irods#6251] use find_package for fmt (main)

CMakeLists.txt
In service of irods/irods#6251
=> [irods/irods#6251] use find_package for fmt (4-3-stable)

src/irsync.cpp
Addresses irods/irods#5359
Companion PR: https://github.com/irods/irods/pull/7534
=> [irods/irods#5359] irsync: Fix --link handling (main)

src/irsync.cpp
Cherry-picked from #443 
Companion PR: irods/irods#7538
=> [irods/irods#5359] irsync: Fix --link handling (4-3-stable)

.clang-format, src/iadmin.cpp
Needed for for https://github.com/irods/irods/pull/7533
Tests will fail without this change.
=> Changed iadmin rmgroup to use new api convention

.clang-format, src/iadmin.cpp
Cherry-pick of https://github.com/irods/irods_client_icommands/pull/447
=> Changed iadmin rmgroup to use new api convention (4-3-stable)

src/irepl.cpp
Addresses irods/irods#6953
Companion PR: https://github.com/irods/irods/pull/7591
=> [irods/irods#6953] irepl: Deprecate "backupMode" (main)

src/irepl.cpp
Addresses https://github.com/irods/irods/issues/6953
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/456
Companion PR: https://github.com/irods/irods/pull/7604
=> [irods/irods#6953] irepl: Deprecate "backupMode" (4-3-stable)

src/iadmin.cpp
identical to https://github.com/irods/irods_client_icommands/pull/459
=> [irods/irods_6363] update quota helptext (4-3-stable)

src/iadmin.cpp
=> [irods/irods#7695] Fix "iadmin modrepl" help text for docs.irods.org (4-3-stable)

src/iadmin.cpp
=> [irods/irods#7695] Fix formatting of "iadmin modrepl" help text (4-3-stable)

src/ierror.cpp, src/iget.cpp, src/iput.cpp, src/irmdir.cpp, src/irule.cpp, src/itree.cpp
=> [irods/irods#7470] Ensure icommands set SP_OPTION (4-3-stable)

src/icd.cpp
=> Add words about IRODS_ENVIRONMENT_FILE to icd help text (4-3-stable)

src/iquota.cpp
=> [irods/irods#7780] iquota: remove unused local variables `printCount` (main)

src/iquota.cpp
=> [irods/irods#7780] iquota: remove unused local variables `printCount` (4-3-stable)

src/itree.cpp
=> [#7761] Fix help text for itree JSON option (main)

test/rules/rulemsiServerMonPerf.r
In service of irods/irods#7760
Companion PR: https://github.com/irods/irods/pull/7830
Companion PR: https://github.com/irods/irods/pull/7843
=> [irods/irods#7760] Remove rulemsiServerMonPerf.r (4-3-stable)

test/rules/rulemsiServerMonPerf.r
In service of https://github.com/irods/irods/issues/7760
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/490
Companion PR: https://github.com/irods/irods/pull/7848
=> [irods/irods#7760] Remove rulemsiServerMonPerf.r (main)

src/irule.cpp
This commit effectively "inlines" `trimPrefix(...)`, as the two locations in this commit are the only call sites for it. Additionally, replaces `trimSpaces(...)` with `trim_left_copy(...)` from boost.
=> [irods/irods#7704] Use boost's trim, don't call `trimPrefix(...)` or `trimSpaces(...)` (main)

src/irule.cpp
=> [irods/irods#7704] Use boost trim, remove deprecated functions (4-3-stable)

src/iadmin.cpp
Fixes all the test cases listed in the ticket (they now return 4).
Pending tests, but I think those need to be included in a PR to the main server(?)
=> [irods/irods7734] iadmin failures now exit non-zero (main)

src/iadmin.cpp
Cherry-pick of https://github.com/irods/irods_client_icommands/pull/506
=> [irods/irods7734] iadmin failures now exit non-zero

src/iquest.cpp
=> [irods/irods#3902] Replace fillGenQueryInpFromStrCond with parse_genquery1_string (main)

bin/igetwild, bin/ilocate, src/ihelp.cpp
Since these are just bash scripts, I think this is sufficient? Let me know if more messages need to be added anywhere else.
=> [irods/irods2524,irods/irods2525] Deprecate ilocate and igetwild (4-3-stable)

src/iqmod.cpp
Seems to be causing the segfault. Will run tests to make sure this doesn't break anything.
=> [irods/irods8120] Remove duplicated rcDisconnect call (main)

CMakeLists.txt, ub-sanitizer-ignorelist.txt
Need to verify ignore is correct.
Companion to irods/irods#8138.
=> [irods/irods#8090] Add Undefined Behavior Sanitizer to Build Options (4-3-stable)

CMakeLists.txt
=> [irods/irods#7286] Remove references to externals-provided libarchive (main)

CMakeLists.txt
In service of irods/irods#7286
=> [irods/irods#7286] Remove references to externals-provided libarchive (4-3-stable)

src/istream.cpp
Companion PR at irods/irods#8180.
All unit/core tests pass.
=> [irods/irods#8166] Fix read/write loop in istream (4-3-stable)

src/istream.cpp
Cherry-pick of #530.
Companion PR at irods/irods#8184.
=> [irods/irods#8166] Fix read/write loop in istream (main)

src/iadmin.cpp
In service of irods/irods#2978
Companion PR: https://github.com/irods/irods/pull/8192
Leaving in draft til companion PR is opened.
=> [irods/irods#2978] iadmin: Add support to "add" a "group" (main)

src/icd.cpp, src/ichksum.cpp, src/ichmod.cpp, src/icp.cpp, src/iput.cpp, src/irsync.cpp
Companion to irods/irods#8141.
=> [irods/irods#8106] Fix memory leaks found in irsync tests (4-3-stable)

src/icd.cpp, src/ichksum.cpp, src/ichmod.cpp, src/icp.cpp, src/iput.cpp, src/irsync.cpp
Cherry-pick of #519. Companion to irods/irods#8206.
=> [irods/irods#8106] Cherry-pick: Free memory of leaking objects found in testing (main)

src/ichksum.cpp, src/iclienthints.cpp
=> Simple tweaks to help text (main)

src/iquest.cpp
=> [irods/irods#7622] Replace examples in iquest help text with link to web page (main)

CMakeLists.txt, src/iadmin.cpp
In service of https://github.com/irods/irods/issues/2978
In service of irods/irods#8203
Companion PR: https://github.com/irods/irods/pull/8220
Cherry-picked from https://github.com/irods/irods_client_icommands/pull/532
Will mark ready for review when companion PR is ready.
=> [irods/irods#2978] iadmin: Add support to "add" a "group" (4-3-stable)

src/imiscsvrinfo.cpp
Requires https://github.com/irods/irods/pull/8236 to be merged first. Leaving as draft until the other one is approved and we agree on a printing format.
Example output:
```
RCAT_ENABLED
relVersion=rods4.90.0
apiVersion=d
rodsZone=tempZone
SSL Info:
notAfter: 2026-02-21 20:05:02 UTC
notBefore: 2025-02-21 20:05:02 UTC
pubkey: RSA Public-Key: (2048 bit)
Modulus:
00:be:c2:60:d8:7a:66:78:48:19:1a:ab:1c:1c:28:
71:94:16:3e:15:a4:93:d5:0f:30:87:c6:b8:d5:35:
c6:50:69:f0:f5:3a:a9:6c:6d:7c:ef:7e:41:22:c0:
24:21:8d:61:2f:78:30:c1:79:7f:66:e0:9b:8b:88:
33:68:16:ef:87:2f:83:4a:bd:c5:89:a8:46:ef:2a:
cd:b8:4c:6d:a9:bc:76:ec:91:8d:d4:eb:f8:b6:97:
c9:11:c2:bc:cc:8b:c7:02:07:d8:39:2a:20:db:01:
54:a1:35:48:d3:c7:4d:1c:92:a7:96:ce:51:0d:43:
87:c8:5a:ff:be:0c:f7:cb:3f:e5:66:73:c6:50:d9: …
```
=> [7986] Print SSL info in imiscsvrinfo (main)

CMakeLists.txt
In service of irods/irods#8326
In service of irods/irods#8327
=> [irods/irods#8326,irods/irods#8327] Remove zmq and avro leftovers (main)

src/iadmin.cpp
=> [irods/irods#8260] Allow modification of access time via iadmin modrepl (main)

src/iinit.cpp
In service of irods/irods#7937
In service of irods/irods#8257
Companion PR: https://github.com/irods/irods/pull/8356
=> [irods/irods#7937,irods/irods#8257] Update auth in iinit (main)

src/iinit.cpp
Depends on irods/irods#8357.
Will test soon.
=> Do not set client-server negotiation policy / Guarantee rodsEnv strings are null-terminated (main)

src/iinit.cpp
In service of irods/irods#8257
Companion PR: https://github.com/irods/irods/pull/8383
=> [irods/irods#8257] iinit updates for native auth (main)

src/iinit.cpp
Addresses irods/irods#7948
Companion PR: https://github.com/irods/irods/pull/8394
=> [irods/irods#7948] iinit: Only non-native schemes force prompt (4-3-stable)

CMakeLists.txt
In service of irods/irods#8102
In service of irods/irods#8332
=> [irods/irods#8102,irods/irods#8332] Bump CMake policy requirements, migrate to system fmt (main)

CMakeLists.txt, src/icp.cpp, src/iput.cpp, test/rules/rulemsiDataObjCopy.r, test/rules/rulemsiDataObjPut.r
In service of irods/irods#8361
In draft mode until testing is complete
=> [irods/irods#8361] Install icommands to subdir in clients dir, add symlinks

CMakeLists.txt
In service of irods/irods#8361
=> [irods/irods#8361] Change name of links staging directory (fix building with ninja)

CMakeLists.txt
=> [irods/irods8451] Bump version number to 5.0.0 (main)

CMakeLists.txt
=> [irods/irods#8539] Bump version to 5.0.1 (main)

src/igroupadmin.cpp
=> [irods/irods#8583] Fix help text for igroupadmin (5-0-stable)

src/igroupadmin.cpp
=> [irods/irods#8583] Fix help text for igroupadmin (4-3-stable)

src/itouch.cpp
Taking suggestions on the wording/extra details we want to go with.
=> [8673] Update itouch help text to be more explicit (4-3-stable)

src/itouch.cpp
Cherry-pick of https://github.com/irods/irods_client_icommands/pull/592
=> [irods/irods8673] Update itouch help text to be more explicit (main)

src/itouch.cpp
Cherry-pick of https://github.com/irods/irods_client_icommands/pull/592
=> [irods/irods8673] Update itouch help text to be more explicit (5-0-stable)
